# Generated by Django 5.2.7 on 2025-10-31 02:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Decreto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_api', models.IntegerField(unique=True)),
                ('numero', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ley',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_api', models.IntegerField(unique=True)),
                ('titulo', models.CharField(max_length=500)),
                ('abrogada', models.BooleanField(default=False)),
                ('comentario', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_api', models.IntegerField(unique=True)),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_api', models.IntegerField(unique=True)),
                ('fecha_ppo', models.DateField()),
                ('ruta_archivo', models.URLField()),
                ('comentario', models.TextField(blank=True, null=True)),
                ('estatus', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('decretos', models.ManyToManyField(blank=True, to='leyes.decreto')),
                ('ley', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='leyes.ley')),
            ],
        ),
        migrations.AddField(
            model_name='ley',
            name='temas',
            field=models.ManyToManyField(related_name='leyes', to='leyes.tema'),
        ),
    ]
