# Generated by Django 5.2.7 on 2025-10-31 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leyes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='decreto',
            name='id_api',
        ),
        migrations.RemoveField(
            model_name='historial',
            name='id_api',
        ),
        migrations.RemoveField(
            model_name='ley',
            name='id_api',
        ),
        migrations.RemoveField(
            model_name='tema',
            name='id_api',
        ),
        migrations.AlterField(
            model_name='decreto',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='historial',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ley',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tema',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
