# Generated by Django 5.2.7 on 2025-10-31 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leyes', '0002_remove_decreto_id_api_remove_historial_id_api_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historial',
            old_name='ruta_archivo',
            new_name='rutaArchivo',
        ),
    ]
