# Generated by Django 5.2.7 on 2025-10-31 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leyes', '0003_rename_ruta_archivo_historial_rutaarchivo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ley',
            old_name='temas',
            new_name='tema',
        ),
    ]
