# Generated by Django 5.2.7 on 2025-10-31 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leyes', '0004_rename_temas_ley_tema'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tema',
            old_name='nombre',
            new_name='tema',
        ),
    ]
