# Generated by Django 5.2.7 on 2025-10-31 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leyes', '0006_decreto_external_id_alter_decreto_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tema',
            name='external_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='tema',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
